<?php

  function wv_custom_follow_networks_alter(&$networks, $uid = 0){
    $networks[$uid]['imdb'] = array(
      'title' => t('IMDB'),
      'domain' => 'imdb.com',
    );

    $networks[$uid]['drupal'] = array(
      'title' => t('Drupal.org'),
      'domain' => 'drupal.org',
    );

    $networks[$uid]['github'] = array(
      'title' => t('github.com'),
      'domain' => 'github.com',
    );

    $networks[$uid]['etsy'] = array(
      'title' => t('etsy.com'),
      'domain' => 'etsy.com',
    );
  }
